CREATE TABLE IF NOT EXISTS item_inventory (
    item_inventory_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE,
    box_number INTEGER,
    description VARCHAR(4000),
    active BOOLEAN,
    for_sale BOOLEAN,
    new_or_used VARCHAR(20),
    completeness VARCHAR(50),
    item_condition_id INTEGER,
    box_condition_id INTEGER,
    instructions_condition_id INTEGER,
    sealed BOOLEAN,
    built_once BOOLEAN
);
