package net.bricklink.data.lego.dao;

import lombok.RequiredArgsConstructor;
import net.bricklink.data.lego.dto.Transaction;
import net.bricklink.data.lego.dto.TransactionItem;
import net.bricklink.data.lego.ibatis.mapper.TransactionsMapper;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.util.List;

@Component
@RequiredArgsConstructor
public class TransactionDao {
    private final TransactionsMapper transactionsMapper;

    public void insertTransaction(Transaction transaction) {
        transactionsMapper.insertTransaction(transaction);
    }

    public void insertTransactionItem(TransactionItem transactionItem) {
        transactionsMapper.insertTransactionItem(transactionItem);
    }

    public List<Transaction> findByTransactionDate(LocalDate date) {
        return transactionsMapper.findByTransactionDate(date);
    }

    public List<Transaction> findByAutoGeneratedAndTransactionDate(LocalDate date) {
        return transactionsMapper.findByAutoGeneratedAndTransactionDate(date);
    }
}
