CREATE TABLE if not exists bricklink_inventory (
  bl_inventory_id int(11) NOT NULL AUTO_INCREMENT,
  uuid char(32) NOT NULL,
  box_id int(11) NOT NULL,
  box_index int(11) NOT NULL,
  bl_item_number varchar(10) NOT NULL,
  inventory_id int(11) DEFAULT NULL,
  item_type varchar(20) NOT NULL,
  color_id smallint(6) DEFAULT NULL,
  color_name varchar(50) DEFAULT NULL,
  quantity smallint(6) NOT NULL,
  new_or_used varchar(1) NOT NULL,
  completeness varchar(1) NOT NULL,
  unit_price decimal(7,2) NOT NULL,
  bind_id int(11) DEFAULT NULL,
  description varchar(1024) DEFAULT NULL,
  remarks varchar(1024) DEFAULT NULL,
  bulk smallint(6) DEFAULT NULL,
  is_retain BOOLEAN NOT NULL,
  is_stock_room BOOLEAN NOT NULL,
  stock_room_id varchar(1) NOT NULL,
  date_created datetime DEFAULT NULL,
  my_cost decimal(7,2) DEFAULT NULL,
  sale_rate tinyint(4) DEFAULT NULL,
  tier_quantity1 smallint(6) DEFAULT NULL,
  tier_quantity2 smallint(6) DEFAULT NULL,
  tier_quantity3 smallint(6) DEFAULT NULL,
  tier_price1 decimal(7,2) DEFAULT NULL,
  tier_price2 decimal(7,2) DEFAULT NULL,
  tier_price3 decimal(7,2) DEFAULT NULL,
  my_weight decimal(5,2) DEFAULT NULL,
  sealed BOOLEAN NOT NULL,
  order_id int(11) DEFAULT NULL,
  fixed_price BOOLEAN DEFAULT NULL,
  for_sale BOOLEAN DEFAULT NULL,
  built_once BOOLEAN DEFAULT NULL,
  box_condition_id int(11) DEFAULT NULL,
  instructions_condition_id int(11) DEFAULT NULL,
  internal_comments varchar(1024) DEFAULT NULL,
  update_timestamp datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  last_synchronized_timestamp datetime DEFAULT NULL,
  extended_description varchar(1024) null,
  extra_description varchar(1024) null,
  CONSTRAINT bl_inventory_id_pk PRIMARY KEY (bl_inventory_id),
  CONSTRAINT inventory_index_index_1 UNIQUE (box_id,box_index),
  CONSTRAINT uuid_index UNIQUE (uuid)
);

ALTER TABLE bricklink_inventory ADD FOREIGN KEY (bl_item_number) REFERENCES bricklink_item(bl_item_number);